# Common Functions for creating and parsing config files 
from collections import defaultdict
import os
from pathlib import Path
import yaml
import logging
import tempfile
logger = logging.getLogger(__name__)

class RunArgs:
    """ Arguments for running a Fusesoc simulation, used to control which stages are executed and how. """
    def __init__(
        self,
        system,
        target="default",
        tool="verilator",
        setup=True,
        build=False,
        run=False,
        clean=True,
        verbose=False,
        no_export=True,
        backendargs=None,
        flag=None,
        mapping={},
        lockfile=None,
    ):
        # Core options
        self.system = system
        self.target = target
        self.tool = tool

        # Stage control
        self.setup = setup
        self.build = build
        self.run = run

        # Behaviour flags
        self.clean = clean
        self.no_export = no_export
        self.verbose = verbose

        # Optional fields expected by run()
        self.backendargs = backendargs or []
        self.flag = flag or []
        self.mapping = mapping
        self.lockfile = lockfile

class SimConfig:
    """ Simulation configuration extracted from the EDAM file generated by Fusesoc. """
   
    def __init__(self, edam, edam_path:Path):
        self.edam = edam
        self.edam_path = edam_path

    @property
    def toplevel(self):
        return self.edam["toplevel"]
    
    @property
    def test_module(self):
        cocotb_sources = [
            f["name"] for f in self.edam["files"]
            if f["file_type"] == "cocotbSource"
        ]

        if cocotb_sources:
            if len(cocotb_sources) > 1:
                logger.warning(
                    "Multiple cocotbSource files found %s, using first: '%s'",
                    cocotb_sources, cocotb_sources[0]
                )
            return Path(cocotb_sources[0]).stem

        # Fall back to a python file matching test_{toplevel}.py
        expected = f"test_{str(self.toplevel).replace("_wtb","")}.py"
        python_sources = [
            f["name"] for f in self.edam["files"]
            if f["file_type"] == "pythonSource"
        ]
        match = next((f for f in python_sources if Path(f).name == expected), None)

        if match is None:
            raise FileNotFoundError(
                f"No cocotbSource found and no Python file matching '{expected}' "
                f"in EDAM. Available python sources: {python_sources}"
            )
        
        return Path(match).stem

    @property
    def verilog_sources(self):
        base = self.edam_path.parent
        return [
           str((base / f["name"]).resolve())
            for f in self.edam["files"]
            if f["file_type"] in ("verilogSource", "systemVerilogSource")
        ]

    @property
    def test_files(self):
        base = self.edam_path.parent
        return [
            str((base / f["name"]).resolve())
            for f in self.edam["files"]
            if (f["file_type"] == "pythonSource" or f["file_type"] == "cocotbSource")
        ]

def get_edam_path(vlnv:str, base_dir="."):
    filename = vlnv.replace(":", "_") + ".eda.yml"
    # Build full path
    return Path(base_dir) / filename

def parse_edam(edam_path:Path): 
    # FIXME - do some validation on the filename
    if not edam_path.exists():
        raise FileNotFoundError(f"EDAM file not found: {edam_path}")
    # Load YAML
    with open(edam_path, "r") as f:
        data = yaml.safe_load(f)

    return data

def fusesoc_setup(args):
    from fusesoc.fusesoc import Fusesoc
    from fusesoc.main import args_to_config, list_cores, run, _get_core
    from fusesoc.config import Config

    Fusesoc.init_logging(verbose=True, monochrome=False, log_file=None)

    if not getattr(args, "config", None):
        config = Config("fusesoc.conf")
    else:
        config = Config(args.config) 

    args.ssh_trustfile = None
    args.no_export = True

    args_to_config(args, config)
    fs = Fusesoc(config)

    cores = fs.get_cores()
    vlnv = _get_core(fs, args.top_core)
    
    if vlnv is None:
        raise ValueError(f"Top-level core '{args.top_core}' not found in any registered library.")
    else:
        print(f"\nFound Top-level core VLNV: {vlnv}")
        print(f"Found {len(cores)} cores in total.")

    # EDAM Generation (edalize)
    run_args = RunArgs(
        system=args.top_core,
        target=args.target,
        no_export=True,
        setup=True,
        clean=True
    )
    run(fs, run_args)

    flags = {"target": args.target or "default"}
    build_dir = fs.get_work_root(vlnv, flags)
    
    # delete the extra files
    from pathlib import Path
    for file in Path(build_dir).rglob("*.vc"):
        file.unlink()
    for file in Path(build_dir).rglob("Makefile"):
        file.unlink()

    # Parse the EDAM file output (intermediate representation)
    edam_path = get_edam_path(str(vlnv), base_dir=build_dir)
    edam      = parse_edam(edam_path)

    config = SimConfig(edam, edam_path) 

    print(f"\n Test files: {config.test_files}")

    # print(f"\n Verilog Files: {config.}")
    # print(f"Parsed EDAM file for {vlnv}: {len(edam.get('files', []))} files found.")
   
    return edam

# FIXME add more validation and parsing logic
def load_edam_to_config(config_path:str):
    """ Read a config file and return the relevant arguments"""
    
    path = Path(config_path).resolve()
    config = SimConfig(parse_edam(path), path)
    return config

    